# Generated by Django 4.2.3 on 2023-11-19 13:46

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="TRX",
                unique=True,
            ),
        ),
    ]
