# Generated by Django 4.2.3 on 2023-11-21 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_user_total_deposit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="description",
            new_name="transaction_id",
        ),
    ]
