# Generated by Django 4.2.3 on 2023-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_deposit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="confirmed",
        ),
    ]
