# Generated by Django 4.2.3 on 2023-11-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_remove_transaction_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, max_length=25)),
                ("wallet_address", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ijklmno12345",
                        length=10,
                        max_length=20,
                        prefix="WDR",
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
