# Generated by Django 4.2.3 on 2023-12-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0013_deposit_currency_deposit_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("hourly", "hourly"),
                ],
                default="daily",
                max_length=16,
            ),
        ),
    ]
