# Generated by Django 4.2.3 on 2023-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0014_transaction_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="percentage_return",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=1000
            ),
        ),
    ]
