# Generated by Django 4.2.3 on 2023-12-11 16:54

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0016_user_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345", length=10, max_length=20, prefix="meta"
            ),
        ),
    ]
