# Generated by Django 4.2.3 on 2023-12-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0018_alter_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
