# Generated by Django 4.2.3 on 2023-12-15 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0020_alter_user_referral_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_code",
        ),
    ]
