# Generated by Django 4.2.3 on 2023-11-19 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_plan_least_amount_plan_max_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="invested_amount",
        ),
    ]
