# Generated by Django 4.2.3 on 2023-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_plan_invested_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="invested_amount",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=1000
            ),
        ),
    ]
