# Generated by Django 4.2.3 on 2023-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_plan_invested_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("hourly", "hourly"),
                ],
                default="in_review",
                max_length=16,
            ),
        ),
    ]
